swagger: "2.0"
info:
  description: "Spécification de la gestion des utilisateurs"
  version: "1.0.0"
  title: "Gestion des utilisateurs"
  contact:
    email: "yohan.boichut@univ-orleans.fr"
host: "localhost:8089"
tags:
- name: "utilisateurs"
  description: "Tout sur les utilisateurs"
schemes:
- "http"
paths:
  /gestionutilisateursws:
      delete:
        tags:
        - "Données générales"
        summary: "Réinitialisation des données dans le web-services"
        operationId: "reinitialisation"
        responses:
          200:
              description: "Toutes les données ont été réinitialisées"

  /gestionutilisateursws/utilisateurs:
    post:
      tags:
      - "utilisateurs"
      summary: "crée un nouvel utilisateur"
      description: ""
      operationId: "creerUtilisateur"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Utilisateur qui doit être enregistré dans le système"
        required: true
        schema:
          $ref: "#/definitions/UtilisateurDTO"
      responses:
        201:
          description: "successful operation"
          headers:
              pseudo:
                type: string
                description: Le pseudo validé.
        409:
          description: "Utilisateur déjà existant"

    get:
      tags:
      - "utilisateurs"
      summary: "récupère tous les utilisateurs du Web-service"
      operationId: "getUtilisateurs"
      produces:
      - "application/json"
      responses:
        200:
          description: "Tous les utilisateurs du Web service"
          schema:
            type: array
            items:
              $ref: "#/definitions/UtilisateurDTO"

  /gestionutilisateursws/utilisateurs/{id}:
    get:
      tags:
      - "utilisateurs"
      summary: "Récupération d'un utilisateur par son ID"
      description: "Retourne un utilisateur"
      operationId: "getUtilisateurById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID de l'utilisateur à retourner"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/UtilisateurDTO"
        404:
          description: "Utilisateur non existant"

          
definitions:
  UtilisateurDTO:
    type: "object"
    properties:
        identifiant:
          type: "integer"
          format: "int64"
        nom:
          type: "string"
        prenom:
          type: "string"
